export const peppa = [
  'Candy_Cat.webp',
  'Captain_Dog_ID.webp',
  'Daddy_Pig-0.webp',
  'Daddy_Rabbit-0.webp',
  'DannyDog.webp',
  'Freddy_Fox.webp',
  'Georgecerdo.webp',
  'Gerald_Giraffe.webp',
  'Grandpa_Pig-0.webp',
  'Granny_Pig.webp',
  'Imageedit_2_8838419266.webp',
  'Imageedit_5_9473473591.webp',
  'Mummy_Dog-0.webp',
  'Mummy_Pig.webp',
  'Peggi_Panda.webp',
  'PicsArt_01-20-11.24.03.webp',
  'PicsArt_01-20-11.26.23.webp',
  'PicsArt_01-20-11.56.38.webp',
  'PicsArt_01-21-05.31.05.webp',
  'PicsArt_01-21-05.56.02.webp',
  'PicsArt_01-21-06.01.59.webp',
  'Pippa.webp',
  'SuzySheep.webp',
  'Wendy_Wolf.webp',
  'ZoeZebra.webp',
  'mamma-klef.webp',
  'molly-mouse.webp',
  'opa-klef.webp',
  'opa-mummel.webp',
].map((url) => `peppa-pig-cards/${url}`)

export const basic = [
  'ali-karimiboroujeni-6cVU1DcG5dA-unsplash.jpg',
  'artem-mihailov-YBzGaC4sak4-unsplash.jpg',
  'fatane-rahimi-2cXZQ862gws-unsplash.jpg',
  'jasmin-chew-c6AU3Oe2inc-unsplash.jpg',
  'komarov-egor-tA4JkT_21N8-unsplash.jpg',
  'max-griss-4z8BkcEwwWM-unsplash.jpg',
  'palm.jpg',
  'vicky-ng-yIh0i6TYGrs-unsplash.jpg',
].map((url) => `basic/${url}`)
