import { NumberInputHandlers } from '@mantine/core'
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { RootState, AppThunk } from '../../app/store'
// import { fetchCount } from './counterAPI';

export type Move = {}

export type Card = {
  index: number
  flipped?: boolean
  locked?: boolean
  imageUrl: string
}

const images = [
  'images/ali-karimiboroujeni-6cVU1DcG5dA-unsplash.jpg',
  'images/artem-mihailov-YBzGaC4sak4-unsplash.jpg',
  'images/fatane-rahimi-2cXZQ862gws-unsplash.jpg',
  'images/jasmin-chew-c6AU3Oe2inc-unsplash.jpg',
  'images/komarov-egor-tA4JkT_21N8-unsplash.jpg',
  'images/max-griss-4z8BkcEwwWM-unsplash.jpg',
  'images/palm.jpg',
  'images/vicky-ng-yIh0i6TYGrs-unsplash.jpg',
]

export interface GameState {
  gameState: 'notStarted' | 'started' | 'ended'
  player1: number
  player2: number
  turn: number | ''
  gameId: string
  activePlayer: 'player1' | 'player2' | ''
  gameStartedAt: number
  moves: Move[]
  activeCards: number[]
  // activeCards: [number, number] | [number] | []
  cards: Card[] | []
}

const initialState: GameState = {
  gameState: 'notStarted',
  player1: 0,
  player2: 0,
  turn: '',
  gameId: '',
  activePlayer: '',
  gameStartedAt: 0,
  moves: [],
  activeCards: [], // every click, add here if empty or length = 2 else
  cards: [], // new game, fill this
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount: number) => {
//     const response = await fetchCount(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   }
// );

function shuffle(array: { index: number; imageUrl: string }[]) {
  array.sort(() => Math.random() - 0.5)
  return array
}

export const gameSlice = createSlice({
  name: 'game',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    createGame: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      const unique = Array(6)
        .fill('')
        .map((_, i) => ({
          imageUrl: images[i],
          index: i,
        }))
      const allCards = [...unique, ...unique]
      state.cards = shuffle(allCards).map((card, i) => ({
        ...card,
        index: i,
      }))
      state.turn = 0
      state.gameId = `game-${Date.now()}`
      state.activePlayer = 'player1'
      state.gameStartedAt = Date.now()
      state.gameState = 'started'
    },
    flipCard: (state, action: PayloadAction<number>) => {
      const selectedIndex = action.payload
      if (state.cards[selectedIndex]) {
        state.cards[selectedIndex].flipped = true
      }
      state.activeCards.push(selectedIndex)
      state.moves.push(selectedIndex)
    },
    lockCards: (
      state,
      action: PayloadAction<{ first: number; second: number }>
    ) => {
      if (action.payload?.first && action.payload?.second) {
        state.cards[action.payload.first].locked = true
        state.cards[action.payload.second].locked = true
        debugger
        if (state.activePlayer !== '') {
          state[state.activePlayer] += 1
        }
        state.activeCards = []
      }
    },
    resetActive: (
      state,
      action: PayloadAction<{ first: number; second: number }>
    ) => {
      if (
        typeof action.payload?.first !== 'undefined' &&
        typeof action.payload?.second !== 'undefined'
      ) {
        state.cards[action.payload.first].flipped = false
        state.cards[action.payload.second].flipped = false
        state.activeCards = []
      }
    },
    changeTurn: (state) => {
      state.activePlayer =
        state.activePlayer === 'player1' ? 'player2' : 'player1'
      state.turn = state.turn || 0 + 1
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = 'loading'
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle'
  //       state.value += action.payload
  //     })
  //     .addCase(incrementAsync.rejected, (state) => {
  //       state.status = 'failed'
  //     })
  // },
})

export const { createGame, flipCard, lockCards, resetActive, changeTurn } =
  gameSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const turn = (state: RootState) => state.game.turn
export const cards = (state: RootState) => state.game.cards
export const activeCards = (state: RootState) => state.game.activeCards
export const game = (state: RootState) => state.game

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState())
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount))
//     }
//   }

export default gameSlice.reducer
